# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
lwjgl = "3.4.2"
joml = "1.10.9"
jspecify = "1.0.1"
junit-jupiter = "5.11.1"

[libraries]
lwjgl-bom = { module = "org.lwjgl:lwjgl-bom", version.ref = "lwjgl" }
# Versions come from the BOM above, so these are deliberately version-less.
lwjgl-core = { module = "org.lwjgl:lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl" }
# For textures
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb" }
joml = { module = "org.joml:joml", version.ref = "joml" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

[bundles]
lwjgl = ["lwjgl-core", "lwjgl-glfw", "lwjgl-opengl", "lwjgl-stb"]
